### ISSUE TITLE
Sync Desktop - App Hub Outdated

### ISSUE THREAD

**Issue by VeSeaOfficial** [vechain/app-hub#114]
**Describe the bug**
When selecting "View More" from the Sync landing page you are directed to [App Hub](https://apps.vechain.org/), which is both:
1. Not synced in test/prod (different apps)
2. Not up to date with recently deployed dApps

**To Reproduce**
1. Open Sync Desktop
2. Click "View More" under the applications
3. Review dApps
4. Compare in testnet/mainnet

**Expected result:**
Up-to-date listing of applications similar to the behavior of the VeChainThor "Discover" tab

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**
**Sync:** v1.3.1
**Connex**:  1.4.2
**Electron**:  3.0.16
**Chrome**:  66.0.3359.181
**V8**:  6.6.346.32

**Comment by XJWX89** [comment]
hi @VeSeaOfficial , thanks for bringing up this issue. currently, APPhub is a ***progressive web app(pwa)***, thus, it requires to `reload` the page (APPhub) to sync in all the apps. we will improve the user experience that notifying the user when new content is available
